# Identificadores del proyecto
sonar.projectKey=hipstagram-core
sonar.projectName=Hipstagram
sonar.projectVersion=1.0

# Directorio raíz a escanear (punto es todo el proyecto)
sonar.sources=.

# Exclusiones críticas (¡No tocar para no romper el escáner!)
sonar.exclusions=**/node_modules/**, **/*.spec.ts, **/dist/**, **/uploads/**, **/.git/**

# Forzar el análisis en TypeScript y JavaScript
sonar.sourceEncoding=UTF-8

// # Identificadores del proyecto
sonar.projectKey=hipstagram-core
sonar.projectName=Hipstagram
sonar.projectVersion=1.0

# Escanear específicamente las carpetas de código (evita escanear archivos basura de la raíz)
sonar.sources=backend, frontend

# Exclusiones críticas (¡No tocar para no romper el escáner!)
sonar.exclusions=**/node_modules/**, **/*.spec.ts, **/dist/**, **/uploads/**, **/.git/**

# Forzar el análisis en TypeScript y JavaScript
sonar.sourceEncoding=UTF-8

# Le decimos a SonarQube dónde leer la cobertura de pruebas que generó Jest en el paso 3
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info