# Identificadores del proyecto
sonar.projectKey=hipstagram-core
sonar.projectName=Hipstagram
sonar.projectVersion=1.0

# Directorio raíz a escanear (punto es todo el proyecto)
sonar.sources=.

# Exclusiones críticas (¡No tocar para no romper el escáner!)
sonar.exclusions=**/node_modules/**, **/*.spec.ts, **/dist/**, **/uploads/**, **/.git/**

# Forzar el análisis en TypeScript y JavaScript
sonar.sourceEncoding=UTF-8